<style>
	
	.site-main-font,
	.woocommerce-loop-product__title,
	.single-product .product .woocommerce-gb_accordion ul.accordion .accordion-item .accordion-content .shop_attributes tr th,
	body.single .post .entry-meta__item--tags a,
	.archive-header .archive-description p,
	a span.count,
	.wpml-ls-current-language ul li a span,
	.wcml-cs-active-currency ul li a
	{ 
		font-family: 
		<?php echo "'" . GBT_Opt::getOption('main_font')['font-family'] . "'," ?>
		sans-serif;
	}

	/* Global */
	.site-secondary-font,
	h1,
	h2,
	h3,
	h4,
	h5,
	h6,
	blockquote,
	button,
	.button,
	input[type="submit"],
	thead,
	th,
	label,
	.label,
	
	/* WC */
	.site-header-style-1 .header-branding .site-title a,
	.site-header-style-2 .header-branding .site-title a,
	.woocommerce .wc-tabs,
	.onsale,
	.products_ajax_button,
	.posts_ajax_button,
	.products_ajax_loader,
	.stock,
	.woocommerce.woocommerce-wishlist .wishlist_table tr td.wishlist-empty,
	.woocommerce.woocommerce-wishlist .wishlist_table tr td.product-stock-status,
	.woocommerce-account .woocommerce .woocommerce-MyAccount-navigation ul li a,
	.woocommerce-account.woocommerce-view-order .woocommerce-MyAccount-content .woocommerce-order-details .order_details tfoot tr td .amount,
	.woocommerce-account.woocommerce-view-order .woocommerce-MyAccount-content .woocommerce-order-details .order_details tfoot tr td .tax_label,
	.addresses .woocommerce-Address .woocommerce-Address-title .edit,
	.woocommerce-orders-table tbody tr td.woocommerce-orders-table__cell-order-number,
	.woocommerce-account.woocommerce-edit-account .edit-account fieldset legend,
	.woocommerce-LostPassword a,
	.lost_password a,
	.woocommerce .after-cart-empty-title,
	.woocommerce-pagination li .page-numbers,
	.product .yith-wcwl-add-to-wishlist,
	.product .entry-summary .getbowtied-single-product-share,
	.product .entry-summary .woocommerce-Reviews .commentlist .comment_container .comment-text p.meta .woocommerce-review__author,
	.product .entry-summary .woocommerce-Reviews #review_form_wrapper #review_form .comment-reply-title,
	.comments-area .comment-list .comment article.comment-body .comment-meta .comment-author b.fn,
	.comments-area .comment-list .comment article.comment-body .reply > a,
	.comments-area .comment-list .comment article.comment-body .comment-meta .comment-metadata .edit-link .comment-edit-link,
	.comments-area .comment-list .pingback .edit-link .comment-edit-link,
	.comments-area .comments-pagination .nav-links .page-numbers,
	form.cart .quantity input.qty,
	body.attachment .site-content .nav-links a,
	.entry-summary .price,
	.entry-summary .woocommerce-grouped-product-list-item__price,
	.product.product-type-variable .variations_form .variations .reset_variations,
	.product .woocommerce-gb_accordion ul.accordion .accordion-item .accordion-title,
	body.woocommerce-cart .woocommerce .cart-empty,
	body.woocommerce-cart.woocommerce-page .woocommerce .woocommerce-cart-form .cart_item .product-quantity .quantity input,
	.getbowtied_new_product,
	.tooltip,
	.woocommerce .woocommerce-message,
	.woocommerce .woocommerce-error,
	.woocommerce .woocommerce-info,
	body.woocommerce-cart .cart-collaterals .cart-subtotal td,
	body.woocommerce-cart .cart-collaterals .order-total td,
	body.woocommerce-cart .cart-collaterals .cart_totals tr.shipping .woocommerce-shipping-calculator p a.shipping-calculator-button,
	body.woocommerce-checkout .woocommerce table.woocommerce-checkout-review-order-table tr.order-total td,
	body.woocommerce-checkout .woocommerce table.woocommerce-checkout-review-order-table tr.cart-subtotal td .amount,
	body.woocommerce-checkout .woocommerce .woocommerce-checkout-payment .payment_methods label,
	body.woocommerce-checkout.woocommerce-order-received .woocommerce-order .woocommerce-order-overview li,
	body.woocommerce-checkout.woocommerce-order-received .woocommerce-order .woocommerce-bacs-bank-details .wc-bacs-bank-details li,
	body.woocommerce-checkout.woocommerce-order-received .woocommerce-order .woocommerce-order-details .woocommerce-table--order-details tfoot tr td .amount,
	#getbowtied_woocommerce_quickview .getbowtied_qv_content .site-content .product .go_to_product_page,
	body.woocommerce-cart .cart-collaterals .cart_totals table.shop_table tr.cart-discount .woocommerce-remove-coupon,
	.woocommerce-account .woocommerce-Payment ul.payment_methods li label,
	.gbt-mega-menu-content .megamenu_cta,
	.gbt-mega-menu-content .megamenu_bottom_links > a,
	.gbt-mega-menu-content .megamenu_icon_list > a > span,
	.woocommerce-mini-cart__total,
	.site-header-style-1 .header-cart .minicart .widget_shopping_cart .woocommerce-mini-cart__empty-message,
	.site-header-style-1 .header-content .header-line-3 .gbt-mega-dropdown-wrapper.is-active .gbt-mega-dropdown .gbt-mega-dropdown-content ul li a,
	.site-header-style-2 .header-cart .minicart .widget_shopping_cart .woocommerce-mini-cart__empty-message,
	.site-header-style-2 .header-content .header-line-3 .gbt-mega-dropdown-wrapper.is-active .gbt-mega-dropdown .gbt-mega-dropdown-content ul li a,
	body.single .post .entry-meta__item--inline,
	body.single .nav-links__item span,
	body.single .post .page-links,
	.gbt-mega-menu-content .megamenu_blog_wrapper .megamenu_posts .megamenu_post .megamenu_post_title,
	.gbt-mega-menu-content .megamenu_blog_wrapper .megamenu_posts_category_list > a,
	.gbt-mega-menu-content .megamenu_category_wrapper .megamenu_category_list .megamenu_category > a,
	.getbowtied_qv_loading,
	.header_search_ajax_results .product-search-heading,
	.header_search_ajax_results .view-all,
	.header-mobiles-wrapper .header-mobiles-content .gbt-mega-dropdown-content .is-drilldown ul li > a,
	.header-mobiles-wrapper .header-mobiles-content .header-mobiles-primary-menu .is-drilldown ul li > a,
	.header-mobiles-wrapper .header-mobiles-menu > a,
	.header-mobiles-wrapper .header-mobiles-content .header-mobiles-ecomm-menu ul li a span,
	.header-mobiles-wrapper .header-mobiles-content .header-mobiles-large-categories .megamenu_icon_list a span,
	.wpml-ls-current-language a span,
	.wcml-cs-active-currency a,
	.vc_btn3,
	.gbt_custom_link,
	.shortcode_getbowtied_slider,
	.widget_calendar,
	.widget-area select,
	.comments-area .comment-list li.pingback
	{
		font-family: 
		<?php echo "'" . GBT_Opt::getOption('secondary_font')['font-family'] . "'," ?>
		sans-serif;
	}

</style>
